'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const { createMockZernio } = require('../support/mock-zernio.cjs')
const { createPostingMock } = require('../support/mock-posts.cjs')
const { buildApp, launchApp, ROOT } = require('../support/electron-app.cjs')

const KEY = 'automation-e2e-key'
const FFMPEG = fs.existsSync(path.join(ROOT, 'engine-bin', 'ffmpeg')) ? path.join(ROOT, 'engine-bin', 'ffmpeg') : 'ffmpeg'

/** Picks an option from one of the app's dropdowns (a combobox button with a listbox menu). */
async function choose(page, combobox, name) {
  await combobox.click()
  await page.getByRole('listbox').getByRole('option', { name, exact: true }).click()
}

test('add library clips, review TikTok, and run a mixed-platform automation', { timeout: 180_000 }, async (t) => {
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-automation-e2e-'))
  const clip = path.join(work, 'new_clip.mp4')
  execFileSync(FFMPEG, ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'color=c=green:s=360x640:d=4:r=15',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=4', '-shortest', '-c:v', 'mpeg4', '-q:v', '8',
    '-c:a', 'aac', '-movflags', '+faststart', clip])
  const run = path.join(work, 'userData', 'BridgeClip', 'automation-library-run')
  fs.mkdirSync(run, { recursive: true })
  const clips = ['first.mp4', 'second.mp4'].map((name) => {
    const target = path.join(run, name)
    fs.copyFileSync(clip, target)
    return target
  })
  fs.writeFileSync(path.join(run, 'job_output.json'), JSON.stringify({
    job_id: 'automation-library-run', source_video_title: 'Automation library run',
    source_video_description: 'A conversation about speech recognition for reliable automation.',
    clips: clips.map((file, index) => ({ clip_index: index, s3_url: `file://${file}`, duration_ms: 4000,
      start_time_ms: index * 4000, end_time_ms: (index + 1) * 4000, virality_score: 0.8 - index * 0.1,
      summary: index === 0 ? 'First library clip' : 'Second library clip' }))
  }))
  const posting = createPostingMock()
  let researchCalls = 0; let batchWritingCalls = 0; let failLargeBatches = false
  const mock = await createMockZernio({ apiKey: KEY, extraRoutes: [...posting.routes,
    { method: 'POST', path: '/speech', auth: false, handler: (ctx) => ctx.json(200, { text: 'Accurate transcripts make automations reliable.' }) },
    { method: 'POST', path: '/chat', auth: false, handler: (ctx) => {
      if (ctx.body.tools) { researchCalls++; return ctx.json(200, { choices: [{ message: { content: 'Relevant terms: speech recognition and reliable automation.', annotations: [{ type: 'url_citation', url_citation: { title: 'Recognition guide', url: 'https://example.com/recognition' } }] } }] }) }
      const input = JSON.parse(ctx.body.messages[1].content)
      if (failLargeBatches && input.clips?.length === 5) return ctx.json(503, { error: 'test provider interruption' })
      const posts = input.platforms.map(({ platform }) => ({ platform, title: platform === 'youtube' ? 'Why Transcript Accuracy Matters for Automation' : null, caption: 'Accurate transcripts make automations reliable. Here is the connection to speech recognition.', tags: platform === 'youtube' ? ['speech recognition'] : [], categoryId: platform === 'youtube' ? '28' : null, topicTag: null, evidence: 'Accurate transcripts make automations reliable.' }))
      if (input.clips) batchWritingCalls++
      ctx.json(200, { choices: [{ message: { content: JSON.stringify(input.clips ? { clips: input.clips.map((clip) => ({ id: clip.id, posts })) } : { posts }) } }] })
    } }
  ] })
  const [profile] = mock.state.profiles
  mock.addAccount('youtube', profile._id, { username: 'channel' })
  mock.addAccount('instagram', profile._id, { username: 'creator' })
  mock.addAccount('tiktok', profile._id, { username: 'tiktok-creator' })
  let session = null
  t.after(async () => {
    await session?.close()
    await mock.close()
    fs.rmSync(work, { recursive: true, force: true })
  })
  const appDir = buildApp(path.join(work, 'app'))
  session = await launchApp({ appDir, userDataDir: path.join(work, 'userData'), mock, env: { BRIDGECLIP_E2E_TRANSCRIPTION_URL: `${mock.url}/speech`, BRIDGECLIP_E2E_OPENROUTER_URL: `${mock.url}/chat`, PATH: `${process.env.PATH}${path.delimiter}${path.join(ROOT, 'engine-bin')}` } })
  const { page, app } = session
  await page.evaluate((key) => window.bridgeclip.settings.replaceApiKey('zernioApiKey', key), KEY)
  await page.evaluate(() => window.bridgeclip.settings.replaceApiKey('openrouterApiKey', 'e2e-only-key'))
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByLabel('Automation name').fill('BridgeMind')
  await page.locator('form').getByRole('button', { name: 'Create' }).click()
  await page.getByRole('heading', { name: 'Content bank' }).waitFor()

  await page.getByRole('button', { name: 'New profile' }).click()
  await page.getByLabel('New profile name').fill('Another profile')
  await page.locator('form').getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByText('Profile “Another profile” created.').waitFor()
  await choose(page, page.getByLabel('Zernio profile'), profile.name)
  await page.getByRole('button', { name: 'Connect', exact: true }).click()
  await page.getByRole('heading', { name: 'Accounts', exact: true }).waitFor()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('heading', { name: 'Content bank' }).waitFor()
  assert.equal(await page.getByLabel('Zernio profile').textContent(), profile.name)

  await page.getByRole('checkbox', { name: /@channel/ }).check()
  await page.getByRole('checkbox', { name: /@creator/ }).check()
  await page.getByRole('checkbox', { name: /@tiktok-creator/ }).check()
  assert.equal(await page.getByRole('switch', { name: 'Write captions with AI' }).getAttribute('aria-checked'), 'false')
  await page.getByRole('radiogroup', { name: 'YouTube visibility' }).getByRole('radio', { name: 'Unlisted' }).click()
  await page.locator('input[type="time"]').fill('23:59')
  await page.getByRole('button', { name: 'Add time' }).click()
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Changes saved.').waitFor()
  await page.getByRole('switch', { name: 'Automation on' }).click()
  await page.getByText('BridgeMind is on.').waitFor()

  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Library/ }).click()
  await page.getByText('Automation library run').click()
  await page.getByRole('checkbox', { name: 'Select all clips' }).click()
  await page.getByRole('button', { name: 'Add 2 to automation' }).click()
  await page.getByRole('dialog', { name: 'Add to content bank' }).getByRole('button', { name: 'Add 2 clips' }).click()
  await page.getByRole('button', { name: 'View bank' }).click()
  await page.getByRole('heading', { name: 'Content bank' }).waitFor()
  const clipTitle = page.getByText('First library clip', { exact: true })
  await clipTitle.waitFor()
  await app.evaluate(({ clipboard }) => clipboard.writeText('before-copy'))
  const titleBounds = await clipTitle.boundingBox()
  assert.ok(titleBounds)
  await page.mouse.move(titleBounds.x + 2, titleBounds.y + titleBounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(titleBounds.x + 85, titleBounds.y + titleBounds.height / 2, { steps: 10 })
  await page.mouse.up()
  const selection = await page.evaluate(() => window.getSelection()?.toString() ?? '')
  const selectionStyles = await clipTitle.evaluate((element) => ({
    text: getComputedStyle(element).userSelect,
    parent: getComputedStyle(element.parentElement).userSelect,
    scroll: getComputedStyle(document.getElementById('page-scroll')).userSelect
  }))
  assert.ok(selection.trim(), `content text can be selected (${JSON.stringify(selectionStyles)})`)
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+C' : 'Control+C')
  assert.equal(await app.evaluate(({ clipboard }) => clipboard.readText()), selection, 'the selected content copies to the clipboard')
  assert.equal(await page.getByRole('button', { name: 'Run now' }).isDisabled(), true)
  const filters = page.getByRole('radiogroup', { name: 'Filter clips' })
  await filters.getByRole('radio', { name: 'Ready 0', exact: true }).click()
  await page.getByText('No clips match this filter.').waitFor()
  await filters.getByRole('radio', { name: 'TikTok review 2', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: 'Review TikTok', exact: true }).count(), 2)
  await filters.getByRole('radio', { name: 'All 2', exact: true }).click()
  await page.getByRole('button', { name: 'Review TikTok', exact: true }).first().click()
  const review = page.getByRole('dialog', { name: 'Review for TikTok' })
  const audience = review.getByLabel('Who can view this video')
  await audience.waitFor()
  assert.equal(await audience.textContent(), 'Choose who can view', 'privacy has no default')
  assert.equal(await review.getByRole('button', { name: 'Approve for automation' }).isDisabled(), true)
  assert.equal(posting.state.uploads.length, 0)
  await review.getByLabel('TikTok caption').fill('Reviewed TikTok caption #Clips')
  await choose(page, audience, 'Everyone')
  const consent = review.getByRole('checkbox', { name: /By posting, you agree/ })
  const previewConsent = review.getByRole('checkbox', { name: 'I reviewed this clip and caption for TikTok' })
  await consent.check()
  await review.getByRole('switch', { name: 'Send to your TikTok inbox', exact: true }).click()
  assert.equal(await consent.isChecked(), false, 'changing delivery mode requires consent again')
  await review.getByRole('switch', { name: 'Send to your TikTok inbox', exact: true }).click()
  await previewConsent.check()
  await review.getByLabel('TikTok caption').fill('Edited again before approval')
  assert.equal(await previewConsent.isChecked(), false, 'changing the caption requires reviewing it again')
  await review.getByLabel('TikTok caption').fill('Reviewed TikTok caption #Clips')
  await consent.check()
  await previewConsent.check()
  await review.getByRole('button', { name: 'Approve for automation' }).click()
  await page.getByText('TikTok review saved.').waitFor()
  assert.equal(posting.state.uploads.length, 0)
  await page.getByRole('button', { name: 'Edit TikTok', exact: true }).click()
  await audience.waitFor()
  assert.equal(await review.getByLabel('TikTok caption').inputValue(), 'Reviewed TikTok caption #Clips')
  assert.equal(await audience.textContent(), 'Choose who can view', 'reopened reviews require a fresh audience choice')
  await review.getByRole('button', { name: 'Cancel', exact: true }).click()
  const firstClipRow = page.locator('li').filter({ has: page.getByText('First library clip', { exact: true }) })
  await firstClipRow.getByRole('button', { name: 'Review TikTok', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Run now' }).isDisabled(), true, 'cancelled edits leave the clip awaiting approval')
  await firstClipRow.getByRole('button', { name: 'Review TikTok', exact: true }).click()
  await audience.waitFor()
  assert.equal(await review.getByLabel('TikTok caption').inputValue(), 'Reviewed TikTok caption #Clips', 'cancelling preserves the last reviewed caption')
  await choose(page, audience, 'Everyone')
  await review.getByRole('checkbox', { name: /By posting, you agree/ }).check()
  await review.getByRole('checkbox', { name: 'I reviewed this clip and caption for TikTok' }).check()
  await review.getByRole('button', { name: 'Approve for automation' }).click()
  await review.waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Run now' }).click()
  await page.getByText('Run finished. Check the content bank for the result.').waitFor()

  assert.equal(posting.state.uploads.length, 1)
  assert.equal(posting.state.creates.length, 1)
  assert.deepEqual(posting.state.creates[0].body.platforms.map((target) => target.platform), ['youtube', 'instagram', 'tiktok'])
  assert.equal(posting.state.creates[0].body.platforms[0].platformSpecificData.visibility, 'unlisted')
  assert.equal(posting.state.creates[0].body.platforms[2].customContent, 'Reviewed TikTok caption #Clips')
  assert.equal(await page.getByRole('button', { name: 'Run now' }).isDisabled(), true, 'the remaining clip requires its own TikTok review')
  await page.getByRole('checkbox', { name: /@tiktok-creator/ }).uncheck()
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Changes saved.').waitFor()
  await page.getByRole('button', { name: 'Enhance', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Enhance title & caption' })
  await dialog.getByRole('button', { name: 'Generate draft' }).waitFor()
  await page.waitForFunction(() => document.querySelector('input[id$="-source-title"]')?.value === 'Automation library run')
  assert.equal(await dialog.getByLabel('Original description', { exact: true }).inputValue(), 'A conversation about speech recognition for reliable automation.')
  await dialog.getByRole('button', { name: 'Generate draft' }).click()
  dialog = page.getByRole('dialog', { name: 'Review enhanced metadata' })
  await dialog.getByText('Why Transcript Accuracy Matters for Automation', { exact: true }).waitFor()
  assert.equal(posting.state.creates.length, 1, 'enhancing never publishes')
  await dialog.getByText('Context & research · complete').click()
  await dialog.getByText('Recognition guide', { exact: false }).waitFor()
  if (process.env.BRIDGECLIP_ENHANCEMENT_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_ENHANCEMENT_SCREENSHOT })
  await dialog.getByRole('button', { name: 'Review later' }).click()
  await page.getByRole('button', { name: 'Run now' }).click()
  await page.getByText('Review the next clip’s enhanced metadata draft: apply or discard it before posting.', { exact: true }).first().waitFor()
  assert.equal(posting.state.creates.length, 1, 'pending draft holds the queue')
  await page.getByRole('button', { name: 'Review draft' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Apply metadata' }).click()
  await page.getByText('Why Transcript Accuracy Matters for Automation', { exact: true }).waitFor()
  const saved = await page.evaluate(() => window.bridgeclip.automations.list())
  assert.equal(saved[0].content[1].metadataDraft, null)
  assert.equal(saved[0].content[1].generatedMetadata[0].title, 'Why Transcript Accuracy Matters for Automation')
  assert.equal(posting.state.creates.length, 1, 'applying copy does not publish immediately')
  await page.evaluate(async ({ run }) => {
    const [automation] = await window.bridgeclip.automations.list()
    await window.bridgeclip.automations.addLibraryClips(automation.id, run, [0, 1])
  }, { run })
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('button', { name: 'Enhance by source video' }).click()
  await page.getByLabel('Original video', { exact: true }).waitFor()
  assert.match(await page.getByLabel('Original video', { exact: true }).textContent(), /Automation library run · 2 clips/)
  if (process.env.BRIDGECLIP_BATCH_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_BATCH_SCREENSHOT })
  await page.getByRole('button', { name: 'Enhance 2 clips from this video' }).click()
  await page.getByText(/2 drafts ready to review/).waitFor()
  assert.equal(batchWritingCalls, 1, 'one writing request for two clips')
  assert.equal(researchCalls, 1, 'batch reuses the source research from individual enhancement')
  assert.equal(posting.state.creates.length, 1, 'batch does not publish')
  assert.equal(await page.getByRole('button', { name: 'Review draft', exact: true }).count(), 2)
  // A failed five-clip request must not prevent the later batch from running.
  await page.evaluate(async ({ run }) => {
    const [automation] = await window.bridgeclip.automations.list()
    for (let batch = 0; batch < 3; batch++) await window.bridgeclip.automations.addLibraryClips(automation.id, run, [0, 1])
  }, { run })
  failLargeBatches = true
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('button', { name: 'Enhance by source video' }).click()
  await page.getByRole('button', { name: 'Enhance 6 clips from this video' }).click()
  await page.getByText(/1 drafts ready to review · 5 failed · 0 already handled · 0 not attempted/).waitFor()
  const afterFailure = await page.evaluate(() => window.bridgeclip.automations.list())
  assert.equal(afterFailure[0].content.filter((item) => item.metadataError).length, 5)
  assert.equal(afterFailure[0].content.at(-1).metadataDraft.posts.length, 2)
  assert.equal(posting.state.creates.length, 1)
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByText(/Metadata enhancement failed:/).first().waitFor()


})
