const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const { buildApp, launchApp, ROOT } = require('../zernio/support/electron-app.cjs')
const fixture = require('../fixtures/editor/project.json')

test('review editor refines candidates, restores discards, edits captions and bakes only ready clips', { timeout: 180000 }, async (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-editor-e2e-'))
  const userDataDir = path.join(root, 'user-data'), library = path.join(userDataDir, 'BridgeClip'), run = path.join(library, 'review-run')
  fs.mkdirSync(run, { recursive: true })
  const ffmpeg = fs.existsSync(path.join(ROOT, 'engine-bin/ffmpeg')) ? path.join(ROOT, 'engine-bin/ffmpeg') : 'ffmpeg'
  execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=640x360:rate=30',
    '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000', '-t', '45', '-c:v', process.platform === 'darwin' ? 'h264_videotoolbox' : 'libx264',
    '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-movflags', '+faststart', path.join(run, 'editor-source.mp4')])
  fs.copyFileSync(path.join(run, 'editor-source.mp4'), path.join(run, 'editor-preview.mp4'))
  const project = structuredClone(fixture); project.width = 640; project.height = 360; project.duration_ms = 45000
  project.transcript.push(...Array.from({ length: 50 }, (_, i) => ({ start_ms: 15000 + i * 500, end_ms: 15500 + i * 500, text: `Surrounding transcript line ${i + 1}.` })))
  // The first candidate has a known failed review; all questions still belong in the editor.
  fs.writeFileSync(path.join(run, 'editor-project.json'), JSON.stringify(project))
  fs.writeFileSync(path.join(run, 'transcript.json'), JSON.stringify({ segments: project.transcript.map((s) => ({ start_time_ms: s.start_ms, end_time_ms: s.end_ms, text: s.text, words: s.text.split(' ').map((word, i, words) => ({ word, start_time_ms: Math.round(s.start_ms + i * (s.end_ms - s.start_ms) / words.length), end_time_ms: Math.round(s.start_ms + (i + 1) * (s.end_ms - s.start_ms) / words.length) })) })) }))
  fs.writeFileSync(path.join(run, 'job_output.json'), JSON.stringify({ job_id: 'review-run', source_video_url: 'local.mp4', source_video_title: project.title,
    source_video_duration_seconds: 45, clips: [], total_clips: 0, editor_project: true }))
  fs.writeFileSync(path.join(userDataDir, 'settings.json'), JSON.stringify({ version: 6, outputDirectory: library, pythonPath: path.join(ROOT, 'engine/.venv/bin/python'), openrouterApiKey: '', zernioApiKey: '' }))
  const appDir = buildApp(path.join(root, 'app'))
  for (const dir of ['engine', 'bridge', 'engine-bin']) if (fs.existsSync(path.join(ROOT, dir))) fs.symlinkSync(path.join(ROOT, dir), path.join(appDir, dir), 'junction')
  const session = await launchApp({ appDir, userDataDir })
  t.after(async () => {
    await session.page.mouse.up().catch(() => {})
    // A failed assertion can leave an unsaved edit or a captured pointer.
    const stop = setTimeout(() => session.app.process().kill('SIGTERM'), 5000)
    try { await session.close() } finally { clearTimeout(stop); fs.rmSync(root, { recursive: true, force: true }) }
  })
  const { app, page } = session
  const shots = process.env.BRIDGECLIP_E2E_SHOTS
  if (shots) fs.mkdirSync(shots, { recursive: true })
  page.setDefaultTimeout(12000)
  const errors = []; page.on('pageerror', (e) => errors.push(e.message))
  await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; w.setSize(1500, 950); if (process.env.BRIDGECLIP_E2E_SHOTS) w.show() })
  await page.getByRole('button', { name: /^Library/ }).click()
  const libraryCard = page.locator('article').filter({ has: page.getByRole('button', { name: `Open ${project.title}`, exact: true }) })
  await libraryCard.getByLabel('Editing: 2 clips left to finish', { exact: true }).waitFor()
  if (shots) await page.screenshot({ path: path.join(shots, 'library-editing-candidates.png') })
  // Jobs uses the same Library landing rules for a review run with no exports.
  await page.getByRole('button', { name: 'Jobs', exact: true }).first().click()
  await page.getByTitle('Open in Library', { exact: true }).click()
  const editor = page.getByRole('region', { name: 'Clip editor' })
  await editor.waitFor()
  assert.equal(await page.locator('button[aria-current="page"]').getAttribute('aria-label'), 'Library')
  await page.waitForFunction(() => document.querySelector('.editor-source-frame video')?.readyState >= 2)
  const stage = page.locator('.editor-stagebar .editor-status')
  assert.equal(await stage.innerText(), 'Refining')
  assert.equal(await page.getByRole('button', { name: 'Bake captions', exact: true }).isDisabled(), true)
  const reopenFromLibrary = async (remaining) => {
    await page.getByRole('button', { name: /^Library/ }).first().click()
    if (remaining > 0) await libraryCard.getByLabel(`Editing: ${remaining} clip${remaining === 1 ? '' : 's'} left to finish`, { exact: true }).waitFor()
    else if (remaining === 0) {
      // The preview finishes after saved editor progress has been read.
      await libraryCard.locator('img').first().waitFor()
      assert.equal(await libraryCard.locator('[aria-label^="Editing:"]').count(), 0)
    }
    await page.getByRole('button', { name: new RegExp(project.title) }).first().click()
  }
  // Without exports, reopening skips the first discarded candidate.
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await reopenFromLibrary(1)
  await editor.waitFor()
  assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'Why the ending matters')
  assert.equal(await stage.innerText(), 'Refining')
  assert.equal(await page.locator('.editor-discarded').getAttribute('open'), null)
  // Nothing left to finish opens the list, even if every candidate was discarded.
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await reopenFromLibrary(0)
  await page.getByRole('button', { name: 'Open editor', exact: true }).waitFor()
  assert.equal(await editor.count(), 0)
  assert.equal(await page.getByRole('button', { name: 'Continue editing', exact: true }).count(), 0)
  await page.getByRole('button', { name: 'Open editor', exact: true }).click()
  await editor.waitFor()
  await page.getByRole('button', { name: 'Restore clip', exact: true }).click()
  await page.locator('.editor-discarded summary').click()
  await page.locator('.editor-candidate').filter({ hasText: 'Why the ending matters' }).click()
  await page.getByRole('button', { name: 'Restore clip', exact: true }).click()
  await page.locator('.editor-candidate').filter({ hasText: 'Why the ending matters' }).click()
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.editor-stagebar .editor-status').textContent === 'Discarded')
  assert.equal(await page.getByLabel('Title', { exact: true }).isDisabled(), true)
  assert.equal(await page.getByRole('button', { name: 'Bake captions', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.editor-stagebar .editor-status').textContent === 'Refining')
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await page.getByRole('button', { name: 'Restore clip', exact: true }).click()
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await page.locator('.editor-candidate').filter({ hasText: 'The result' }).click()
  assert.equal(await page.locator('.editor-discarded').getAttribute('open'), null)
  assert.equal(await page.locator('.editor-question').count(), 11)
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.editor-source-frame video').currentTime > 1.5)
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  await page.getByLabel('Title', { exact: true }).fill('My deliberate cut')
  await page.getByText('Review out of date', { exact: true }).waitFor()
  await page.getByLabel('Cut 1 start', { exact: true }).fill('0:02.0')
  await page.getByLabel('Cut 1 start', { exact: true }).press('Enter')
  const seek = async (ms) => {
    await page.getByRole('slider', { name: 'Source timeline', exact: true }).evaluate((el, value) => {
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(el, String(value))
      el.dispatchEvent(new Event('input', { bubbles: true }))
      el.dispatchEvent(new Event('change', { bubbles: true }))
    }, ms)
    await page.waitForFunction((value) => Math.abs(document.querySelector('.editor-source-frame video').currentTime * 1000 - value) < 40, ms)
  }
  // The viewport must not shift while extending a handle. The source allows
  // more time than the initial zoomed timeline, in both directions.
  const dragEdge = async (name, deltaMs) => {
    const handle = page.getByRole('button', { name, exact: true })
    const box = await handle.boundingBox(), track = await page.locator('.editor-track').boundingBox()
    const x = box.x + box.width / 2, y = box.y + box.height / 2
    await page.mouse.move(x, y); await page.mouse.down()
    await page.mouse.move(x + deltaMs / 20000 * track.width, y, { steps: 8 })
    // End label remains at 20s until the drag is released.
    assert.match(await page.locator('.editor-timeline-tools').innerText(), /0:20\.0/)
    await page.mouse.up()
  }
  await dragEdge('Trim start of cut 1', -1000)
  assert.match(await page.getByLabel('Cut 1 start', { exact: true }).inputValue(), /0:0[01]\.[09]/)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('input[aria-label="Cut 1 start"]').value === '0:02.0')
  await dragEdge('Trim end of cut 2', 2000)
  assert.match(await page.getByLabel('Cut 2 end', { exact: true }).inputValue(), /0:1[12]\.[09]/)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('input[aria-label="Cut 2 end"]').value === '0:10.0')
  assert.equal(await page.getByLabel('Cut 2 end', { exact: true }).inputValue(), '0:10.0')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await page.waitForFunction(() => /0:1[12]\.[09]/.test(document.querySelector('input[aria-label="Cut 2 end"]').value))
  assert.match(await page.getByLabel('Cut 2 end', { exact: true }).inputValue(), /0:1[12]\.[09]/)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('input[aria-label="Cut 2 end"]').value === '0:10.0')
  await page.getByRole('button', { name: 'Full source', exact: true }).click()
  assert.equal(await page.getByRole('slider', { name: 'Fine timeline position' }).getAttribute('max'), '45000')
  await page.getByRole('button', { name: 'Zoom to clip', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Play cuts only' }).uncheck()
  await seek(10500)
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.editor-source-frame video').currentTime > 10.8)
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  const watchedUntil = await page.locator('.editor-source-frame video').evaluate((v) => Math.round(v.currentTime * 1000))
  await page.getByRole('button', { name: 'Extend to playhead', exact: true }).click()
  await page.getByText('All changes saved', { exact: true }).waitFor()
  assert.equal(JSON.parse(fs.readFileSync(path.join(run, 'editor-project.json'))).candidates[0].ranges[1][1], watchedUntil)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await seek(528)
  await page.getByRole('button', { name: 'Extend to playhead', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('input[aria-label="Cut 1 start"]').value === '0:00.5')
  assert.equal(await page.getByLabel('Cut 1 start', { exact: true }).inputValue(), '0:00.5')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await seek(3000)
  assert.equal(await page.getByRole('button', { name: 'Extend to playhead', exact: true }).isDisabled(), true)
  await page.getByRole('checkbox', { name: 'Play cuts only' }).check()
  await page.getByRole('button', { name: 'Framing', exact: true }).click()
  const crops = () => page.locator('.editor-crop').evaluateAll(nodes => nodes.map(el => [el.style.left, el.style.top, el.style.width, el.style.height].map(n => parseFloat(n) / 100)))
  const closeCrop = (actual, expected) => actual.forEach((n, i) => assert.ok(Math.abs(n - expected[i]) < 1e-7, `${actual} != ${expected}`))
  const resizeCorner = async (name, corner, scale) => {
    const handle = page.getByRole('button', { name: `Resize ${name} crop from ${corner}`, exact: true })
    const handleBox = await handle.boundingBox(), cropBox = await handle.locator('..').boundingBox()
    const x = handleBox.x + handleBox.width / 2, y = handleBox.y + handleBox.height / 2
    await page.mouse.move(x, y); await page.mouse.down()
    await page.mouse.move(x + (corner.endsWith('right') ? 1 : -1) * cropBox.width * (scale - 1),
      y + (corner.startsWith('bottom') ? 1 : -1) * cropBox.height * (scale - 1), { steps: 8 })
    await page.mouse.up()
  }
  const originalCrop = (await crops())[0]
  assert.equal(await page.locator('.editor-crop-corner').count(), 4)
  await page.getByRole('button', { name: 'Mark ready', exact: true }).click()
  await resizeCorner('output', 'top-left', .75)
  const resizedCrop = (await crops())[0]
  assert.ok(resizedCrop[2] < originalCrop[2] && resizedCrop[3] < originalCrop[3])
  assert.ok(Math.abs(resizedCrop[0] + resizedCrop[2] - originalCrop[0] - originalCrop[2]) < 1e-7)
  assert.ok(Math.abs(resizedCrop[1] + resizedCrop[3] - originalCrop[1] - originalCrop[3]) < 1e-7)
  assert.equal(await stage.innerText(), 'Refining')
  // One gesture, including all its pointer moves, takes only one undo/redo.
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  closeCrop((await crops())[0], originalCrop)
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  closeCrop((await crops())[0], resizedCrop)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Split', exact: true }).last().click()
  assert.equal(await page.locator('.editor-crop-corner').count(), 8)
  const splitCrops = await crops()
  await resizeCorner('top', 'bottom-right', .7)
  const splitTop = await crops()
  assert.ok(splitTop[0][2] < splitCrops[0][2]); closeCrop(splitTop[1], splitCrops[1])
  await resizeCorner('bottom', 'top-left', .8)
  const splitBoth = await crops()
  assert.ok(splitBoth[1][2] < splitTop[1][2]); closeCrop(splitBoth[0], splitTop[0])
  // Handles win over the other panel's overlapping move area. Keyboard resize
  // edits that panel too, without triggering timeline arrow shortcuts.
  const playheadBeforeResize = await page.getByRole('slider', { name: 'Source timeline' }).inputValue()
  await page.getByRole('button', { name: 'Resize bottom crop from top-left', exact: true }).focus()
  await page.keyboard.press('Shift+ArrowRight')
  assert.ok((await crops())[1][2] < splitBoth[1][2])
  assert.equal(await page.getByRole('slider', { name: 'Source timeline' }).inputValue(), playheadBeforeResize)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  closeCrop((await crops())[1], splitBoth[1])
  const moveBox = await page.getByRole('button', { name: 'Move top crop', exact: true }).boundingBox()
  await page.mouse.move(moveBox.x + moveBox.width / 2, moveBox.y + moveBox.height / 2); await page.mouse.down()
  await page.mouse.move(moveBox.x + moveBox.width / 2 + 20, moveBox.y + moveBox.height / 2 + 12, { steps: 4 }); await page.mouse.up()
  const moved = (await crops())[0]
  assert.ok(moved[0] > splitBoth[0][0] && moved[1] > splitBoth[0][1])
  closeCrop(moved.slice(2), splitBoth[0].slice(2))
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Fit', exact: true }).click()
  assert.equal(await page.locator('.editor-crop-corner').count(), 0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Top', exact: true }).click()
  const horizontal = page.getByRole('slider', { name: 'Horizontal crop position' })
  await horizontal.focus(); await page.keyboard.press('End')
  await page.getByRole('button', { name: 'Bottom', exact: true }).click()
  await page.getByRole('slider', { name: 'Crop zoom' }).focus(); await page.keyboard.press('ArrowRight')
  // Existing layout changes can be retimed without recreating their crops.
  assert.equal(await page.getByLabel('Layout start', { exact: true }).count(), 0)
  await page.getByRole('button', { name: 'Mark ready', exact: true }).click()
  const marker = page.locator('.editor-scene-marker').first()
  await marker.click()
  assert.equal(await stage.innerText(), 'Ready', 'Selecting a layout is not an edit')
  const existingCrops = await crops()
  const layoutStart = page.getByRole('textbox', { name: 'Layout start', exact: true })
  const waitForLayoutStart = (value) => page.waitForFunction(expected => document.querySelector('input[aria-label="Layout start"]')?.value === expected, value)
  assert.equal(await layoutStart.inputValue(), '0:08.0')
  await layoutStart.fill('0:09.0'); await layoutStart.press('Enter')
  await waitForLayoutStart('0:09.0')
  assert.equal(await layoutStart.inputValue(), '0:09.0')
  assert.equal(await stage.innerText(), 'Refining')
  assert.equal(await page.locator('.editor-source-frame video').evaluate(v => v.currentTime), 9)
  ;(await crops()).forEach((crop, i) => closeCrop(crop, existingCrops[i]))
  await layoutStart.fill('invalid'); await layoutStart.press('Enter')
  await waitForLayoutStart('0:09.0')
  assert.equal(await layoutStart.inputValue(), '0:09.0')
  await marker.focus(); await page.keyboard.press('ArrowLeft')
  await waitForLayoutStart('0:08.9')
  assert.equal(await layoutStart.inputValue(), '0:08.9')
  await page.keyboard.press('Shift+ArrowLeft')
  await waitForLayoutStart('0:07.9')
  assert.equal(await layoutStart.inputValue(), '0:07.9')
  const markerBox = await marker.boundingBox(), markerTrack = await page.locator('.editor-track').boundingBox()
  const markerX = markerBox.x + markerBox.width / 2, markerY = markerBox.y + markerBox.height / 2
  await page.mouse.move(markerX, markerY); await page.mouse.down()
  await page.mouse.move(markerX + markerTrack.width / 20, markerY, { steps: 8 })
  await page.mouse.up()
  const draggedTime = await page.locator('.editor-source-frame video').evaluate(v => Math.round(v.currentTime * 1000))
  assert.ok(Math.abs(draggedTime - 8900) < 40, `Drag reached ${draggedTime}ms`)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await waitForLayoutStart('0:07.9')
  assert.equal(await layoutStart.inputValue(), '0:07.9', 'A whole drag takes one undo')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await waitForLayoutStart(`0:08.${Math.floor(draggedTime % 1000 / 100)}`)
  assert.equal(await layoutStart.inputValue(), `0:08.${Math.floor(draggedTime % 1000 / 100)}`)
  await layoutStart.fill('0:09.0'); await layoutStart.press('Enter')
  await waitForLayoutStart('0:09.0')
  await seek(4000)
  await page.getByRole('button', { name: 'New layout here', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Smooth movement', exact: true }).check()
  await page.getByRole('slider', { name: 'Horizontal crop position' }).focus(); await page.keyboard.press('End')
  await page.getByRole('slider', { name: 'Movement duration' }).focus(); await page.keyboard.press('ArrowRight')
  await resizeCorner('bottom', 'bottom-right', .85)
  // A retimed animation stays before its next neighbour and keeps its settings.
  await layoutStart.fill('0:20.0'); await layoutStart.press('Enter')
  await waitForLayoutStart('0:08.9')
  assert.equal(await layoutStart.inputValue(), '0:08.9')
  assert.equal(await page.locator('.editor-source-frame video').evaluate(v => v.currentTime), 8.999)
  assert.equal(await page.getByRole('slider', { name: 'Movement duration' }).inputValue(), '700')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await waitForLayoutStart('0:03.9')
  assert.equal(await layoutStart.inputValue(), '0:03.9')
  // Merely focusing a rounded timecode must not round its saved milliseconds.
  await layoutStart.focus(); await layoutStart.press('Tab')
  await page.getByRole('button', { name: 'Preview movement', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.editor-source-frame video').currentTime > 4.4)
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  await page.getByText('All changes saved', { exact: true }).waitFor()
  const saved = JSON.parse(fs.readFileSync(path.join(run, 'editor-project.json')))
  assert.equal(saved.candidates[0].title, 'My deliberate cut')
  assert.equal(saved.candidates[0].ranges[0][0], 2000)
  assert.equal(saved.candidates[0].scenes[0].layout, 'split')
  assert.ok(saved.candidates[0].scenes[0].crops[0][0] > .3)
  assert.equal(saved.candidates[0].scenes[1].transition_ms, 700)
  assert.equal(saved.candidates[0].scenes[1].at_ms, 3993)
  assert.equal(saved.candidates[0].scenes[2].at_ms, 9000)
  assert.deepEqual(saved.candidates[0].scenes[2].crops, project.candidates[0].scenes[1].crops)
  const savedCrops = await crops()
  if (shots) { fs.mkdirSync(shots, { recursive: true }); await page.screenshot({ path: path.join(shots, 'editor-framing.png') }) }
  await page.getByRole('button', { name: 'Jev', exact: true }).click()
  if (shots) await page.screenshot({ path: path.join(shots, 'editor-review.png') })
  // The monitor stays in place both between captions and on short/long lines.
  const outputCanvas = page.locator('.editor-output-monitor canvas')
  await seek(2508)
  const monitorBounds = await outputCanvas.boundingBox()
  await seek(3300)
  assert.deepEqual(await outputCanvas.boundingBox(), monitorBounds)
  // Caption editing in Transcript pauses playback and requires approval again.
  await page.getByRole('button', { name: 'Mark ready', exact: true }).click()
  await seek(3300)
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  await page.getByRole('button', { name: 'Transcript', exact: true }).click()
  await page.getByRole('button', { name: 'Edit caption at 0:03.0', exact: true }).click()
  assert.equal(await page.locator('.editor-source-frame video').evaluate(v => v.paused), true)
  const caption = page.getByRole('textbox', { name: 'Caption at 0:03.0', exact: true })
  await caption.fill('The corrected moment.')
  await page.waitForFunction(() => document.querySelector('.editor-stagebar .editor-status').textContent === 'Refining')
  assert.equal(await page.getByRole('button', { name: 'Bake captions', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'Reset text', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('textarea[aria-label="Caption at 0:03.0"]').value === 'The event happened.')
  await caption.fill('A much longer caption that spans several lines in the transcript while the output preview stays in exactly the same place.')
  assert.deepEqual(await outputCanvas.boundingBox(), monitorBounds)
  await caption.fill('The corrected moment.')
  if (shots) await page.screenshot({ path: path.join(shots, 'editor-caption-edit.png') })
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Mark ready', exact: true }).click()
  await page.getByRole('button', { name: /^Library/ }).first().click()
  await page.getByRole('button', { name: new RegExp(project.title) }).first().click()
  await editor.waitFor()
  assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'My deliberate cut')
  assert.equal(await stage.innerText(), 'Ready')
  const reopened = JSON.parse(fs.readFileSync(path.join(run, 'editor-project.json')))
  assert.deepEqual(reopened.candidates[0].caption_edits, [{ segment: 1, text: 'The corrected moment.' }])
  assert.equal(reopened.candidates[1].status, 'discarded')
  assert.deepEqual(reopened.candidates[1].caption_edits, [])
  assert.deepEqual(reopened.transcript, project.transcript)
  assert.deepEqual(reopened.candidates[0].scenes, saved.candidates[0].scenes)
  assert.equal(JSON.parse(fs.readFileSync(path.join(run, 'transcript.json'))).segments[1].text, 'The event happened.')
  await page.getByRole('button', { name: 'Framing', exact: true }).click()
  await seek(4000)
  assert.equal(await page.getByRole('checkbox', { name: 'Smooth movement', exact: true }).isChecked(), true)
  assert.equal(await page.getByRole('slider', { name: 'Movement duration' }).inputValue(), '700')
  const reopenedCrops = await crops()
  reopenedCrops.forEach((crop, i) => closeCrop(crop, savedCrops[i]))
  await page.getByRole('button', { name: 'Bake captions', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.editor-stagebar .editor-status').textContent === 'Baked', undefined, { timeout: 90000 })
  const output = JSON.parse(fs.readFileSync(path.join(run, 'job_output.json')))
  assert.equal(output.total_clips, 1)
  assert.equal(output.clips[0].duration_ms, 4800)
  assert.ok(fs.statSync(output.clips[0].s3_url).size > 1000)
  if (shots) execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-ss', '1.2', '-i', output.clips[0].s3_url, '-frames:v', '1', '-y', path.join(shots, 'export-with-captions.png')])
  await page.getByRole('button', { name: 'Exports', exact: true }).click()
  await page.getByRole('button', { name: 'Open editor', exact: true }).waitFor()
  // A baked clip plus only discards lands on the list with a quiet editor action.
  await reopenFromLibrary(0)
  await page.getByRole('button', { name: 'Open editor', exact: true }).waitFor()
  assert.equal(await editor.count(), 0)
  assert.equal(await page.getByRole('button', { name: 'Continue editing', exact: true }).count(), 0)
  if (shots) await page.screenshot({ path: path.join(shots, 'library-finished-clips.png') })
  await page.getByRole('button', { name: 'Open editor', exact: true }).click()
  await editor.waitFor()
  assert.equal(await stage.innerText(), 'Baked')
  // A correction after baking returns to Refining; undo must still save cleanly.
  await seek(3300)
  await page.getByRole('button', { name: 'Transcript', exact: true }).click()
  await page.getByRole('button', { name: 'Edit caption at 0:03.0', exact: true }).click()
  await caption.fill('Another correction.')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByText('All changes saved', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByText('All changes saved', { exact: true }).waitFor()
  assert.equal(await stage.innerText(), 'Refining')
  assert.equal(await page.locator('.editor-transcript-text').filter({ hasText: 'The corrected moment.' }).count(), 1)
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await page.getByText('All changes saved', { exact: true }).waitFor()
  assert.equal(JSON.parse(fs.readFileSync(path.join(run, 'job_output.json'))).total_clips, 1)
  assert.ok(fs.existsSync(output.clips[0].s3_url))
  await page.getByRole('button', { name: 'Restore clip', exact: true }).click()
  // Older exports still open the list when their candidate is being refined again.
  await page.getByRole('button', { name: 'Exports', exact: true }).click()
  await page.getByRole('button', { name: 'Continue editing', exact: true }).waitFor()
  await page.getByRole('button', { name: /^Library/ }).first().click()
  await libraryCard.getByLabel('Editing: 1 clip left to finish', { exact: true }).waitFor()
  await libraryCard.getByText('1 clip', { exact: true }).waitFor()
  if (shots) await page.screenshot({ path: path.join(shots, 'library-editing-with-baked-clip.png') })
  await page.getByRole('button', { name: new RegExp(project.title) }).first().click()
  await page.getByRole('button', { name: 'Continue editing', exact: true }).waitFor()
  await page.getByText('1 clip left to finish', { exact: true }).waitFor()
  assert.equal(await editor.count(), 0)
  if (shots) await page.screenshot({ path: path.join(shots, 'library-clips-to-finish.png') })
  await page.getByRole('button', { name: 'Continue editing', exact: true }).click()
  await editor.waitFor()
  assert.equal(await stage.innerText(), 'Refining')
  assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'My deliberate cut')
  // Follow captions outside the clip too, without moving the whole editor.
  await page.getByRole('checkbox', { name: 'Play cuts only' }).uncheck()
  await seek(30030)
  await page.getByRole('button', { name: 'Transcript', exact: true }).click()
  const pageScroll = await page.locator('#page-scroll').evaluate((el) => el.scrollTop)
  const inspector = page.locator('.editor-inspector-body')
  await inspector.evaluate((el) => { el.scrollTo({ top: 0, behavior: 'instant' }) })
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  await page.waitForFunction(() => {
    const panel = document.querySelector('.editor-inspector-body'), row = document.querySelector('.editor-transcript [aria-current="true"]')
    if (!row || panel.scrollTop <= 0) return false
    const p = panel.getBoundingClientRect(), r = row.getBoundingClientRect()
    return r.top >= p.top && r.bottom <= p.bottom && document.querySelector('.editor-source-frame video').currentTime > 30.6
  })
  await page.getByRole('button', { name: 'Play / pause', exact: true }).click()
  assert.equal(await page.locator('#page-scroll').evaluate((el) => el.scrollTop), pageScroll)
  // Let the native pause event and compositor finish cancelling smooth scroll
  // before simulating a separate manual scroll and seek.
  await page.getByRole('button', { name: 'Play / pause', exact: true }).locator('.lucide-play').waitFor()
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await inspector.evaluate((el) => { el.scrollTo({ top: 0, behavior: 'instant' }) })
  await seek(35013)
  assert.equal(await inspector.evaluate((el) => el.scrollTop), 0, 'Paused seeking leaves manual transcript scrolling alone')
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 760))
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
  if (shots) await page.screenshot({ path: path.join(shots, 'editor-compact.png') })
  assert.deepEqual(errors, [])
})
